backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/img"
display_url: https://expo5.pnptc.events
logo_url: https://expo5.pnptc.events/assets/img/pnp_pri_grn_rgb.svg

collections:
  - name: "pages"
    label: "Pages"
    editor:
     preview: false
    files:
      - label: "Index"
        name: "index"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: 'home'}
          - {label: "Event Date", name: "event_date", widget: "datetime", dateFormat: "YYYY/MM/DD", timeFormat: "HH:mm:ss" }
          - {label: "Intro Claim", name: "claim", widget: markdown }
          - {label: "Intro Information", name: "sub_header", widget: markdown }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: Content, name: content, widget: markdown }
              - { label: Signature, name: signature, widget: boolean }
          - label: "Corporates"
            name: "corporates"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Flashback"
            name: "flashback"
            widget: "object"
            fields:
              - { label: "Intro", name: "intro", widget: "markdown" }
          - label: "Apply"
            name: "apply"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Mediaparter"
            name: "mediapartner"
            widget: "object"
            fields:
              - { label: "Intro", name: "intro", widget: "markdown" }
  - name: "data"
    label: "Data"
    editor:
     preview: false
    files:
      - label: "Information"
        name: "information"
        file: "information.yml"
        fields:
          - { label: "Website Title", name: "title", widget: "string", required: true }
          - { label: "Website Description", name: "description", widget: markdown, required: true }
          - { label: "Website Image", name: "image", widget: "image" }
          - { lable: "Twitter", name: "twitter", widget: "string" }
          - { lable: "Linkedin", name: "linkedin", widget: "string" }
