backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index"
        name: "index"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: 'home'}
          - {label: "Event Date", name: "event_date", widget: "date", format: "YYYY/MM/DD HH:mm:ss" }
          - {label: "Intro Claim", name: "claim", widget: markdown }
          - {label: "Intro Information", name: "sub_header", widget: markdown }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: Content, name: content, widget: markdown }
              - { label: Signature, name: signature, widget: boolean }
