backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/img"
display_url: https://expo5.pnptc.events
logo_url: https://expo5.pnptc.events/assets/img/pnp_pri_grn_rgb.svg

collections:
  - name: "pages"
    label: "Pages"
    editor:
     preview: false
    files:
      - label: "Index"
        name: "index"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: 'home'}
          - {label: "Intro Claim", name: "claim", widget: markdown }
          - {label: "Intro Information", name: "sub_header", widget: markdown }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: Content, name: content, widget: markdown }
              - { label: Signature, name: signature, widget: boolean }
          - label: "Corporates"
            name: "corporates"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Flashback"
            name: "flashback"
            widget: "object"
            fields:
              - { label: "Intro", name: "intro", widget: "markdown" }
          - label: "Apply"
            name: "apply"
            widget: "object"
            fields:
              - { label: "Content", name: "content", widget: "markdown" }
          - label: "Mediaparter"
            name: "mediapartner"
            widget: "object"
            fields:
              - { label: "Intro", name: "intro", widget: "markdown" }
  - name: "data"
    label: "Data"
    editor:
     preview: false
    files:
      - label: "Information"
        name: "information"
        file: "_data/information.yml"
        fields:
          - { label: "Website Title", name: "title", widget: "string", required: true, hint: "The Title of the Website which appears on search engines etc." }
          - { label: "Website Author", name: "author", widget: string }
          - label: "Main language of website"
            name: "language"
            widget: "select"
            options:
              - label: English
                value: en_US
              - label: German
                name: de_DE
          - { label: "Website Description", name: "description", widget: markdown, required: true, hint: "The description which appears on google." }
          - { label: "Website Image", name: "image", widget: "image" }
          - {label: "Event Date", name: "event_date_time", widget: "datetime", dateFormat: "YYYY/MM/DD", timeFormat: "HH:mm:ss" }
          - { lable: "Twitter", name: "twitter", widget: "string" }
          - { lable: "Linkedin", name: "linkedin", widget: "string", hint: "Only enter the subpage of the website, not the entire domain. E. g. https://linkedin.com/{{ this is the part that should be entered }}" }
          - { label: "URL", name: "url", widget: "string", hint: "The entire domain of the website." }
      - label: "Mediapartner"
        name: "mediapartner"
        file: "_data/mediapartner.yml"
        fields:
          - label: "Mediapartners"
            name: "mediapartners"
            widget: "list"
            fields:
              - label: "Name of the Parter"
                name: "name"
                widget: "string"
              - label: "URL of the Partner Website"
                name: "url"
                widget: "string"
              - label: "Logo"
                name: "logo_svg"
                widget: "string"
                hint: "To add a logo please ask the admin of this website as they have to be added manually in the backend."
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Footer Navigation"
            name: "footer"
            widget: "list"
            fields:
              - label: "Name of Link"
                name: "link"
                widget: "string"
                required: true
              - label: "URL to Link"
                name: "url"
                widget: "string"
                required: true
          - label: "Footer Social"
            name: "footer_social"
            widget: "list"
            fields:
              - label: "Font Awesome Icon"
                name: "fa_title"
                widget: "string"
                required: true
                hint: "Fontawesome Icon Classes. Can be found at: https://fontawesome.com/icons"
              - label: "URL to Social Media"
                name: "url"
                widget: "string"
                required: true
